const mongoose = require('mongoose');

const addressSchema = new mongoose.Schema({
  line1: { type: String, required: true },
  line2: { type: String },
  city: { type: String, required: true },
  postalCode: { type: String },
  country: { type: String, required: true },
  phone: { type: String, required: true },
});

const orderItemSchema = new mongoose.Schema({
  product: { type: mongoose.Schema.Types.ObjectId, ref: 'Product', required: true },
  name: { type: String, required: true },
  price: { type: Number, required: true, min: 0 },
  quantity: { type: Number, required: true, min: 1, max: 1000 },
  image: { type: String },
});

const orderSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  // orderNumber is ALWAYS unique - auto-generated before save
  // Can be set by controller OR generated by pre-save hook as fallback
  // Format: "ORD-" + 7-digit number (e.g., "ORD-0000001")
  orderNumber: {
    type: String,
    unique: true,
    sparse: false, // Index all values including zeros
  },
  items: [orderItemSchema],
  totalAmount: { type: Number, required: true, default: 0, min: 0 },
  status: {
    type: String,
    enum: ['pending', 'active', 'shipped', 'delivered', 'cancelled'],
    default: 'pending',
  },
  // Driver assignment and delivery tracking
  assignedDriver: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User',
    default: null 
  },
  assignmentStatus: {
    type: String,
    enum: ['pending', 'accepted', 'rejected'],
    default: 'pending'
  },
  assignmentHistory: [{
    driver: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    status: { type: String, enum: ['assigned', 'accepted', 'rejected'] },
    reason: { type: String },
    timestamp: { type: Date, default: Date.now }
  }],
  deliveryStatus: {
    type: String,
    enum: ['pending', 'assigned', 'in-transit', 'delivered', 'failed'],
    default: 'pending',
  },
  estimatedDeliveryDate: { type: Date },
  actualDeliveryDate: { type: Date },
  // Order type: delivery or pickup
  isPickup: { type: Boolean, default: false },
  pickupLocation: { type: String }, // Store location for pickup orders
  phone: { type: String }, // Phone number for pickup orders
  deliveryAddress: { 
    type: addressSchema, 
    required: function() { 
      return !this.isPickup; // Only required for delivery orders
    }
  },
  payment: {
    method: { type: String, enum: ['cash', 'card', 'online'], default: 'cash' },
    paid: { type: Boolean, default: false },
    transactionId: { type: String },
  },
  // Order notes/comments for staff and admin
  notes: [{
    addedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true
    },
    content: {
      type: String,
      required: true,
      trim: true
    },
    createdAt: {
      type: Date,
      default: Date.now
    }
  }],
}, {
  timestamps: true,
});

// Pre-save hook: Auto-generate unique orderNumber if not already set
// This is a FALLBACK - controller should generate orderNumber before save
// But this ensures we have one even if controller doesn't provide it
orderSchema.pre('save', async function (next) {
  // Only generate if orderNumber not already set
  if (!this.orderNumber) {
    try {
      // Get next order number from counter collection
      const Counter = mongoose.model('Counter', new mongoose.Schema({
        _id: { type: String, required: true },
        sequence_value: { type: Number, default: 0 },
      }, { collection: 'counters' }), 'Counter');

      const counter = await Counter.findByIdAndUpdate(
        'orderNumber', // Counter ID
        { $inc: { sequence_value: 1 } }, // Increment by 1
        { new: true, upsert: true } // Create if doesn't exist, return updated
      );

      // Generate order number: "ORD-" + 7-digit padded number
      this.orderNumber = `ORD-${String(counter.sequence_value).padStart(7, '0')}`;
    } catch (error) {
      // Fallback: Generate timestamp-based unique order number
      // This ensures orders can still be created even if counter fails
      const timestamp = Date.now();
      const random = Math.floor(Math.random() * 10000);
      this.orderNumber = `ORD-${timestamp}${String(random).padStart(4, '0')}`;
    }
  }
  next();
});

// Explicitly define safe indexes (orderNumber unique index is in schema definition)
orderSchema.index({ user: 1, createdAt: -1 }); // For quick user order lookup
orderSchema.index({ status: 1 }); // For status filtering
orderSchema.index({ assignedDriver: 1, deliveryStatus: 1 }); // For driver's orders lookup
orderSchema.index({ createdAt: -1 }); // For sorting

module.exports = mongoose.model('Order', orderSchema);
